Исключения и их обработка
<p>----------------------------------------</p>
Исключениями или исключительными ситуациями (состояниями) называются ошибки, возникшие в программе во время её работы. Все исключения в Java являются объектами. Поэтому они могут порождаться не только автоматически при возникновении исключительной ситуации...
<p>----------------------------------------</p>
Исключениями или исключительными ситуациями (состояниями) называются ошибки, возникшие в программе во время её работы.

Все исключения в Java являются объектами. Поэтому они могут порождаться не только автоматически при возникновении исключительной ситуации, но и создаваться самим разработчиком.

Иерархия классов исключений:

<img data-id="06fa039f-7996-40b2-a9d2-9a54f4c4c68c" data-max-width="850" alt="Исключения и их обработка - 1" src="https://cdn.javarush.com/images/article/06fa039f-7996-40b2-a9d2-9a54f4c4c68c/1024.jpeg">Исключения делятся на несколько классов, но все они имеют общего предка — класс <code>Throwable</code>. Его потомками являются подклассы <code>Exception</code> и <code>Error</code>.

Исключения (<code>Exceptions</code>) являются результатом проблем в программе, которые в принципе решаемы и предсказуемы. Например, произошло деление на ноль в целых числах.

Ошибки (<code>Errors</code>) представляют собой более серьёзные проблемы, которые, согласно спецификации Java, не следует пытаться обрабатывать в собственной программе, поскольку они связаны с проблемами уровня JVM. Например, исключения такого рода возникают, если закончилась память, доступная виртуальной машине. Программа дополнительную память всё равно не сможет обеспечить для JVM.

В Java все исключения делятся на три типа: контролируемые исключения (<code>checked</code>) и неконтролируемые исключения (<code>unchecked</code>), к которым относятся ошибки (<code>Errors</code>) и исключения времени выполнения (<code>RuntimeExceptions</code>, потомок класса <code>Exception</code>).

Контролируемые исключения представляют собой ошибки, которые можно и нужно обрабатывать в программе, к этому типу относятся все потомки класса <code>Exception</code> (но не <code>RuntimeException</code>).

Обработка исключения может быть произведена с помощью операторов <code>try…catch</code>, либо передана внешней части программы. Например, метод может передавать возникшие в нём исключения выше по иерархии вызовов, сам его не обрабатывая.

Неконтролируемые исключения не требуют обязательной обработки, однако, при желании, можно обрабатывать исключения класса <code>RuntimeException</code>.

Откомпилируем и запустим такую программу:

<pre class='lang-java line-numbers'><code>
class Main { 
     public static void main(String[] args) { 
         int a = 4; 
         System.out.println(a/0); 
     } 
}
</code></pre>
В момент запуска на консоль будет выведено следующее сообщение:

<pre class='lang-java line-numbers'><code>
Exception in thread "main" java.lang.ArithmeticException: / by zero 
        at Main.main(Main.java:4)
</code></pre>
Из сообщения виден класс случившегося исключения — <code>ArithmeticException</code>. Это исключение можно обработать:

<pre class='lang-java line-numbers'><code>
class Main { 
     public static void main(String[] args) { 
         int a = 4; 
         try { 
              System.out.println(a/0); 
         } catch (ArithmeticException e) { 
              System.out.println("Произошла недопустимая арифметическая операция"); 
         } 
     } 
}
</code></pre>
Теперь вместо стандартного сообщения об ошибке будет выполняться блок <code>catch</code>, параметром которого является объект e соответствующего исключению класса (самому объекту можно давать любое имя, оно потребуется в том случае, если мы пожелаем снова принудительно выбросить это исключение, например, для того, чтобы оно было проверено каким-то ещё обработчиком).

В блок <code>try</code> при этом помещается тот фрагмент программы, где потенциально может возникнуть исключение.

Одному <code>try</code> может соответствовать сразу несколько блоков catch с разными классами исключений.

<pre class='lang-java line-numbers'><code>
import java.util.Scanner; 
class Main { 
    public static void main(String[] args) { 
     int[] m = {-1,0,1}; 
        Scanner sc = new Scanner(System.in); 
        try { 
            int a = sc.nextInt();     
            m[a] = 4/a; 
            System.out.println(m[a]); 
        } catch (ArithmeticException e) { 
            System.out.println("Произошла недопустимая арифметическая операция"); 
        } catch (ArrayIndexOutOfBoundsException e) { 
            System.out.println("Обращение по недопустимому индексу массива"); 
        } 
    } 
}
</code></pre>
Если запустив представленную программу, пользователь введётся с клавиатуры 1 или 2, то программа отработает без создания каких-либо исключений.

Если пользователь введёт 0, то возникнет исключение класса <code>ArithmeticException</code>, и оно будет обработано первым блоком <code>catch</code>.

Если пользователь введёт 3, то возникнет исключение класса <code>ArrayIndexOutOfBoundsException</code> (выход за приделы массива), и оно будет обработано вторым блоком <code>catch</code>.

Если пользователь введёт нецелое число, например, 3.14, то возникнет исключение класса <code>InputMismatchException</code> (несоответствие типа вводимого значение), и оно будет выброшено в формате стандартной ошибки, поскольку его мы никак не обрабатывали.

Можно, однако, добавить обработчик для класса <code>Exception</code>, поскольку этот класс родительский для всех остальных контролируемых исключений, то он будет перехватывать любые из них (в том числе, и <code>InputMismatchException</code>).

<pre class='lang-java line-numbers'><code>
import java.util.Scanner; 
class Main { 
    public static void main(String[] args) { 
        int[] m = {-1,0,1}; 
        int a = 1; 
        Scanner sc = new Scanner(System.in);        
        try { 
            a = sc.nextInt();     
            m[a-1] = 4/a;
            System.out.println(m[a]); 
        } catch (ArithmeticException e) { 
            System.out.println("Произошла недопустимая арифметическая операция"); 
        } catch (ArrayIndexOutOfBoundsException e) { 
            System.out.println("Обращение по недопустимому индексу массива");       
        } catch (Exception e) { 
            System.out.println("Произошло ещё какое-то исключение"); 
        } 
    } 
}
</code></pre>
Поскольку исключения построены на иерархии классов и подклассов, то сначала надо пытаться обработать более частные исключения и лишь затем более общие. То есть поставив первым (а не третьим) блок с обработкой исключения класса <code>Exception</code>, мы бы никогда не увидели никаких сообщений об ошибке, кроме «Произошло ещё какое-то исключение» (все исключения перехватились бы сразу этим блоком и не доходили бы до остальных).

Необязательным добавлением к блокам <code>try…catch</code> может быть блок <code>finally</code>. Помещенные в него команды будут выполняться в любом случае, вне зависимости от того, произошло ли исключение или нет. При том, что при возникновении необработанного исключения оставшаяся после генерации этого исключения часть программы — не выполняется. Например, если исключение возникло в процессе каких-то длительных вычислений, в блоке <code>finally</code> можно показать или сохранить промежуточные результаты.

Ссылка на первоисточник: <a href='https://kostin.ws/java/java-exceptions.html' rel='nofollow' target='_blank'>Исключения и их обработка</a>