Исключения в Java
<p>----------------------------------------</p>
Когда столкнулся с темой "Исключения", то возникло много вопросов, на которые пришлось искать ответы по различным закоулкам интернета, чтобы понять в деталях, как всё это работает. В результате, я составил собственное объяснение, которое может оказаться более понятным...
<p>----------------------------------------</p>
Когда столкнулся с темой "Исключения", то возникло много вопросов, на которые пришлось искать ответы по различным закоулкам интернета, чтобы понять в деталях, как всё это работает. В результате, я составил собственное объяснение, которое может оказаться более понятным для новичков, только-только столкнувшихся с этим явлением.

<img data-max-width="850" alt="Исключения в Java - 1" src="https://cdn.javarush.com/images/article/94037437-ee15-41ff-a4c7-f275acbcf7aa/original.jpeg">В компьютерах <span class="text-bold">Прерывание</span> – это входящий сигнал для процессора, о том что происходит событие, которое требует немедленной реакции. Сигнал прерывания требует от процессора приостановить выполняемую программу с таким условием, чтобы она могла быть продолжена чуть позже, то есть компьютер должен запомнить всю информацию, связанную с выполнением программы. Подобные прерывания временны, если не носят фатальный характер.

Такие прерывания могут быть вызваны, как программным кодом, так и некоторой функциональностью «железа» (например, просто нажатием клавиш на клавиатуре; таймеры  например, для автоматического отключения компьютера). Количество <span class="text-bold">Прерываний </span>ограничено определённым числом, заложенным при производстве того или иного процессора, то есть под это выделяются специальные «каналы» связи, позволяющие обратиться к процессору в обход всех остальных процессов.

<span class="text-bold">Прерывания</span> так же автоматически генерируются при возникновении ошибки в исполняемом программном коде (например, если встречается деление на ноль). Такие прерывания традиционно называются<em> traps или exceptions</em>. В таких случаях принято говорить: «Exception was thrown», то есть сработало <span class="text-bold">Исключение</span>или <span class="text-bold">Исключение</span> было запущено (брошено), то есть запрос на <span class="text-bold">Прерывание</span> с вопросом «что делать?» послан процессору.

В этот момент процессор останавливает работу, запоминая точку, в которой он остановился, точнее кластер следующей ячейки, информация из которой должна быть выполнена. Запоминается вся цепочка выполненных инструкций и НЕ выполненных. После чего, процессор считывает из памяти инструкции для действий при подобной ошибке. В соответствии с этой инструкцией, он может занести новые значения в определённые кластеры, добавить некоторые цепочки действий или новый цикл (например, цикл возврата или кольцевания) и т.д., то есть в зависимости от ошибки выполняются ранее заложенные инструкции.
  
В систему компьютера само по себе встроено много автоматических Прерываний, которые запускаются через определённое количество времени, например, для контроля запущенных на компьютере процессов или выполнения заложенных будильников, сбора входящих внешних сигналов, различных конвертеров данных. Стоит помнить, что большое количество Прерываний по ряду причин, может окончательно «повесить» систему.

Ошибка в программном коде вызовет в автоматическом режиме Прерывание в процессоре, которое тот попробует обработать в соответствии с заложенными инструкциями. Но не для всех прерываний заложена их обработка или она может выдавать процедуру, которая нас не устраивает, например, просто свернёт приложение. Поэтому в программировании существует возможность организовать собственное прерывание для определённого участка кода, в котором программист потенциально видит вероятность наличия ошибки. В этом случае ошибка обработается внутри программы и не будет обращаться за инструкциями по обработке к процессору. Задание таких блоков организуется созданием Объекта <span class="text-bold">«Исключение» (Exception)</span>.

Этот объект автоматически создаётся в блоке <code>try-catch</code>. В блоке <code>&gt;try</code>производится проверка на наличие ошибки и, если она есть, программа следует в блок <code>catch</code>, где производятся действия предупреждающие или нивелирующие ошибку.

Например, если мы вводим с клавиатуры <span class="text-bold">Числа</span>, которые должны в последствии складываться и вычитаться, то введение с клавиатуры <span class="text-bold">Букв</span> приведёт к невозможности их сложения с <span class="text-bold">Числами</span> (обозначим сумму этих двух переменных буквой S). Поэтому в команде <code>try</code> мы должны проверить способно ли число А, содержащее Цифры, быть сложено с числом Б, содержащим Буквы (то есть S = А + Б ), и если это невозможно, а это невозможно, то должны быть приняты определённые меры, чтобы Ошибки НЕ произошло и к процессору не полетело новое Прерывание с вопросом «что делать?». В случае отсутствия в программе Исключения, её выполнение прервётся процессором. При наличии Исключения, когда оно «поймано» командой <code>try</code>, управление переходит команде <code>catch</code>, которая может задать альтернативный вариант решения, например, не будем складывать эти два числа, а зададим S = А.

<pre class="lang-java line-numbers"><code>
int a = 4;
String b = “hello”;
int S = 0;
 try {
   S = a + b;
   int r = 1;
 } catch (Exception igogo1) {
   S = a;
 }
 return S;
</code></pre>
/* строка «int r = 1;» не выполняется, так как случилась ошибка и программа перенаправляет работу сразу к обработчику исключения  блок catch*/

Таким образом, наличие <span class="text-bold">Исключений</span> – это возможность решить проблему внутри программы, не забрасывая её на уровень процессора. В объект «Исключение», который автоматически создаётся в блоке <code>try</code> при обнаружении ошибки, заносится значение типа ошибки. Назовём его «НашеИсключение» – для нашего конкретного случая с описанием нашей конкретной ошибки. Создатели языка Java, заранее создали некоторый список типовых ошибок и типовые варианты их исправления, то есть в java существует некоторая <span class="text-bold">библиотека Исключений</span>, к которой мы можем обратиться для обработки случившейся ошибки, чтобы самим не писать код обработки и поэтому НашеИсключение скорее всего уже кем-то было описано, поэтому нам надо просто знать название какого из этих исключений вставить в нашу программу для обработки кода, где потенциально может случиться сбой. Если мы ошибёмся и выберем из библиотеки неверное <span class="text-bold">Исключение</span>, то обработчик его не «поймает», ошибка не найдёт решения внутри программы и полетит запрос к процессору. Но существует путь для ленивых. Если мы не знаем название нужного нам исключения из библиотеки, то можем взять общее с названием «<span class="text-bold">Exception</span>», как в вышеописанном примере. Это <span class="text-bold">Исключение </span>способно обработать любой тип ошибки, только не способно выдать конкретную информацию о происшествии, которое мы могли бы занести в логи.

Библиотека ранее написанных <span class="text-bold">Исключений </span>состоит из проверяемых (checked) и <span class="text-bold">непроверяемых</span> (unchecked) <span class="text-bold">Исключений</span>. <span class="text-bold">Проверяемые</span> – это те, которые можно поправить, не обрывая работу программы, то есть, если мы пытаемся открыть файл в папке, в которой его нет, то система даст нам об этом знать, мы можем закинуть файл в нужную папку и продолжить работу программы. То есть по факту к процессору послан запрос на <span class="text-bold">Прерывание</span>, но без вопроса: «ищи, что делать с этой проблемой?!?!». Мы послали Прерывание, которое сами обнаружили, с готовой инструкцией, которую процессор обработал и продолжил выполнение программы. <span class="text-bold">Непроверяемые</span> – это те ошибки, которые нельзя поправить и программа будет закрыта до своего завершения, то есть к процессору полетит запрос на <span class="text-bold">Прерывание</span>, которое в любом случае оборвёт выполнение программы. Единственный смысл прописывать такие исключения в программе – это дать пользователю понять, что произошло, так как, поймав это прерывание, мы можем вывести информационное сообщение на экран из-за чего программа свернулась. Второй причиной ловить такие прерывания является возможность занести их в логи для последующего анализа (вас хакнули, но зато вы знаете через какое место).

Следствием наличия подобных библиотек является необходимость не забыть их подключить. (Список проверяемых и непроверяемых Исключений с библиотеками можно посмотреть, например, <a href="https://www.codejava.net/java-core/exception/java-checked-and-unchecked-exceptions" target="_blank" rel="nofollow">здесь</a>)

Если мы не знаем точно какую библиотеку включить или существует несколько вариантов ошибки, то можем в нескольких <code>catch</code> перечислить нужные Исключения. Система сама выберет правильный обработчик, если он есть в списке. Вместо конкретного <span class="text-bold">Исключения </span>можно написать общее «<span class="text-bold">Exception</span>», которое может обработать любой тип <span class="text-bold">Исключения</span>, если оно не обработалось в предыдущих блоках.

<pre class="lang-java line-numbers"><code>
int a = 4;
String b = “hello”;
int S = 0;
 try {
   S = a + b;
   int r = 1;
 } 
catch(NullPointerException blabla2) {
   System.out.println("Exception handling code for the NullPointerException.");
 } 
catch (ArithmeticException ex1) {
   S = a;
 }
catch(Exception uups1) {
   System.out.println("Exception occured");
 } 
 return S;
</code></pre>
В случае наличия блока <code>try</code> Исключение создаётся автоматически. Если нам надо принудительно в какой-то момент времени вызвать <span class="text-bold">Исключение</span>, то используется команда <code>throw</code>. То есть мы самостоятельно создаём объект <code>new throw</code>… после чего, программа останавливает свою работу, посылает процессору запрос на <span class="text-bold">Прерывание</span> и переносится к разделу программы <code>catch</code>, откуда пытается почерпнуть инструкции по дальнейшим действиям. Создавая вручную <span class="text-bold">Исключение</span>, мы можем указать его конкретный тип из библиотеки:  

<pre><code>
throw new ArithmeticException("Access denied - You must be at least 18 years old.");
</code></pre>
тогда обработчик будет искать блок <code>catch</code>, с именно этим <span class="text-bold">Исключением</span> – искать по всей программе, по всем бокам <code>catch</code>. После команды <code>throw</code> обработки Исключения, весь оставшийся код программы НЕ будет выполнен, за исключением того, который находится в блоке <code>catch</code>. Если обработчик в программе не найден, процессору задаётся вопрос: «решай сам, что делать» и тот прерывает программу. 

 Вызов <code>new throw</code>… может производиться как в блоке <code>&gt;try</code>, так и вне его (в любом месте программы)

<pre class="lang-java line-numbers"><code>
try {
   /* функция или действие, в котором есть сомнения. То есть: «попробуй выполнить это, а если не получится, а, если не получится, запускай режим исключения» */
   throw new CallForException(); /* Назначаем исключение, которое будет работать в случае наличия ошибки в функции, описанной выше. Здесь исключение «CallForException» - берется из библиотеки существующих исключений */
} catch (CallForException ee1) {
   /* Корректируем ошибку, чтобы программа не «отвалилась» или выводим сообщение об ошибке или что-то ещё */
} finally {
   /* этот блок работает всегда независимо от того была ошибка или нет. А если была, то сработало ли решение в catch или нет */
   /* часто используется для подчистки хвостов, например, для закрытия запущенного файла или базы данных */
   /* в ряде случаев блок catch вообще может быть опущен и оставлен только блок finally и наоборот finally может быть опущен и оставлен только catch */
   /* Не допускается использование этого блока в ряде случаев, например, когда функция System.exit() запущена или другие системные Исключения, типа «отключение электроэнергии» и т.п. */
}
</code></pre><h2>Оповещение о наличии Исключения</h2>Ранее написанные кем-то методы могут включать в себя вызов Исключений. Просто на всякий случай программист, который писал код, предупредил последующих программистов, что в написанном им методе может случится ошибка. Так, например, метод создания файла, описанный ниже, предусматривает, что при создании файла может произойти ошибка (нет файла по заданному пути), а значит нужен будет её обработчик:

<pre class="lang-java line-numbers"><code>
public void createFile(String path, String text) throws IOException {
    FileWriter writer = new FileWriter(path, true);
    writer.write(text);
    writer.close();
}
</code></pre>
Но при этом самого обработчика нет, а значит теперь просто вызвать написанный метод в своей программе в обычном режиме мы не сможем. Теперь мы обязаны написать обработчик ошибки и вызывать этот метод в блоке <code>try</code>:

<pre class="lang-java line-numbers"><code>
String filePath = "hello.txt";
String text = "Hello World";
 
try {
    createFile(filePath, text);
} catch (IOException ex) {
    System.err.println("Error creating file: " + ex);
}
</code></pre><h2>Собственные исключения</h2>Существует возможность написать собственные исключения для обработки тех или иных ошибок, если нам недостаточно уже существующих библиотек. Для этого мы просто создаём класс-наследник от класса Исключения

<pre class="lang-java line-numbers"><code>
public class StudentNotFoundException extends Exception {
 
    public StudentNotFoundException (String message) {
        super(message);
    }
}
</code></pre>
При создании собственных исключений следует учитывать два правила:
<ol>
<li>Название нашего класса должно оканчиваться на «Exception»</li>
<li>Класс должен содержать конструктор со строковой переменной, описывающей детали проблемы Исключения. В конструкторе вызывается супер-конструктор с передачей сообщения.</li>
</ol>Пример использования созданного исключения:

<pre class="lang-java line-numbers"><code>
public class StudentManager { 
    public Student find(String studentID) throws StudentNotFoundException {
        if (studentID.equals("123456")) {
            return new Student();
        } else {
            throw new StudentNotFoundException(
                "Could not find student with ID " + studentID);
        }
    }
}
</code></pre>
Отлавливаем это Исключение кодом:

<pre class="lang-java line-numbers"><code>
public class StudentTest {
    public static void main(String[] args) {
        StudentManager manager = new StudentManager();
         try { 
            Student student = manager.find("0000001");
        } catch (StudentNotFoundException ex) {
            System.err.print(ex);
        }
    }
}
</code></pre>
Результатом выполнения программы будет:

<em>StudentNotFoundException: Could not find student with ID 0000001</em>
<h2>Зачем нужно писать Исключения</h2>В 1996 году разбилась ракета <a href="https://en.wikipedia.org/wiki/Cluster_(spacecraft)#Launch_failure" target="_blank" rel="nofollow">Ariane 5</a> из-за неверной конвертации переменной float в переменную integer. Исключений и обработчиков этой ситуации предусмотрено не было.

Если при загрузке файла произошел обрыв связи с интернетом, то наличие Исключения позволит продолжить закачку, после того как соединение восстановится. При отсутствии Исключения закачку придётся начинать заново.
<h2>Использованная литература:</h2><ul>
<li><a href="https://en.wikipedia.org/wiki/Interrupt" target="_blank" rel="nofollow">Interrupt in hardware</a></li>
<li><a href="https://en.wikipedia.org/wiki/Exception_handling" target="_blank" rel="nofollow">Исключения в Вики</a></li>
<li><a href="https://en.wikipedia.org/wiki/Exception_handling_syntax#Java" target="_blank" rel="nofollow">Исключения в Вики для Java</a></li>
<li><a href="https://en.wikibooks.org/wiki/Java_Programming/Throwing_and_Catching_Exceptions" target="_blank" rel="nofollow">Исключение в Вики (кинуть-поймать)</a></li>
<li><a href="https://en.wikipedia.org/wiki/Type_signature#Java" target="_blank" rel="nofollow">Тип "подписи"</a></li>
<li><a href="https://www.codejava.net/java-core/exception/java-checked-and-unchecked-exceptions" target="_blank" rel="nofollow">Проверяемые-непроверяемые исключения</a></li>
<li><a href="https://urvanov.ru/2016/05/02/java-8-%D0%B8%D1%81%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D1%8F" target="_blank" rel="nofollow">urvanov.ru</a></li>
<li><a href="https://beginnersbook.com/2013/04/try-catch-in-java/" target="_blank" rel="nofollow">Исключения для начинающих на WikiBook</a></li>
<li><a href="https://www.w3schools.com/java/java_try_catch.asp" target="_blank" rel="nofollow">блок try-catch</a></li>
<li><a href="https://www.codejava.net/java-core/exception/how-to-create-custom-exceptions-in-java" target="_blank" rel="nofollow">Создание собственных исключений</a></li>
</ul>